### ISSUE TITLE
The program aborts for ANO-RCC-VTZP

### ISSUE THREAD

**Issue by wzkchem5** [msemidalas/autoCABS#1]
When I used the AutoCABS script to generate the CABS basis of either ANO-RCC-VDZP or ANO-RCC-VTZP for Ru (obtained from BSE in either ORCA or Molpro format), the script aborts after the following output:
```
 S orbital exponents and a single outermost decontracted exponent
 [0.02021675]

 P orbital exponents and a single outermost decontracted exponent
 [0.05262899]

 D orbital exponents and a single outermost decontracted exponent
 [0.02643475]

 F orbital exponents and a single outermost decontracted exponent
 [0.073407]

 G orbital exponents and a single outermost decontracted exponent
 [0.2494532]

 H orbital exponents are all with contraction coeff. equal to 1
 []

D orbital exponents were taken as multiples of P-type shells.


F orbital exponents were taken as multiples of D-type shells.


G orbital exponents were taken as multiples of F-type shells.


Geometric mean of P orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of D orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of F orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of G orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of H orbital exponents cannot be calculated from current main orbital exponents: []

Summary of generated AutoCABS exponents
Traceback (most recent call last):
  File "/hsnfs/users/zwang/autoCABS/basis-definitions-and-examples/ANO-RCC-TZP/AutoCABS-generation-geom_mean_tight_and_diffuse_plus_single_layer.py", line 324, in <module>
    print('S\n', np.sort(geom_mean_S)[::-1])
NameError: name 'geom_mean_S' is not defined
```
I could generate the CABS basis of cc-pVTZ or 3-21G correctly using the same workflow, suggesting that this should not be due to my personal error.
Upon careful reading of the autoCABS paper, I realized that for a generally contracted basis set, the autoCABS0 basis set will be empty, which may explain the error. However, in this case autoCABS0+ and all the larger variants of autoCABS are not empty, so it is perfect legitimate for a user to ask for generating an autoCABS basis set for a generally contracted basis set. It would be greatly appreciated if you could make the script applicable to generally contracted basis sets.

**Comment by msemidalas** [comment]
Your feedback is appreciated.

The autoCABS code was updated today:
For generally contracted orbital basis sets with contraction coefficients not equal to 1, e.g., ANO-RCC-VnZP, the autoCABS is generated by using all orbital exponents per subshell, resulting to larger, automatically generated basis sets. This functionality has not been thoroughly tested for energetics and harmonic frequencies.

Please check the generated autoCABS from ANO-RCC-VTZP for Ru inside:
https://github.com/msemidalas/autoCABS/blob/master/basis-definitions-and-examples/ANO-RCC-VDZP-AutoCABS2+-

Hope this is helpful.

Best regards,
Emmanouil Semidalas

**Comment by wzkchem5** [comment]
Thank you very much!

Regards,
Zikuan Wang
