### ISSUE TITLE
NameError: name 'with_contraction_coeff_1_np' is not defined

### ISSUE THREAD

**Issue by isolated-matrix** [msemidalas/autoCABS#3]
Hi there,

I have just tried to use this program and come up with the following error:
```
Traceback (most recent call last):
  File "/Users/xxxx/Documents/Postdoc/calculations/basis-set-generation/fluorine/aug-cc-pvdz-f12-cabs/AutoCABS2+-.py", line 142, in <module>
    S_orbital_exponents_np = process_primitives(S_orbital_exponents_with_contraction_coeff_1_np, S_orbital_exponents_with_contraction_coeff_not_1_np)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Documents/Postdoc/calculations/basis-set-generation/fluorine/aug-cc-pvdz-f12-cabs/AutoCABS2+-.py", line 137, in process_primitives
    return concatenate_and_short(with_contraction_coeff_1_np.flat, outermost_decontracted[0,].flat, kind='mergesort')
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'with_contraction_coeff_1_np' is not defined. Did you mean: 'with_contraction_coeff_1'?
```
Do you have any idea what this error might refer to, or how to fix it?

**Comment by msemidalas** [comment]
Hello,

Could you provide some background? Are you attempting to generate an autoCABS from an aVDZ-F12 OBS for fluorine?
Please send me the file containing your orbital basis set to have a quick look.

 Best,
Emmanouil


   On Monday, December 2, 2024 at 03:32:48 PM GMT+2, isolated-matrix ***@***.***> wrote:  
 
 


Hi there,

I have just tried to use this program and come up with the following error:
Traceback (most recent call last):
  File "/Users/xxxx/Documents/Postdoc/calculations/basis-set-generation/fluorine/aug-cc-pvdz-f12-cabs/AutoCABS2+-.py", line 142, in <module>
    S_orbital_exponents_np = process_primitives(S_orbital_exponents_with_contraction_coeff_1_np, S_orbital_exponents_with_contraction_coeff_not_1_np)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Documents/Postdoc/calculations/basis-set-generation/fluorine/aug-cc-pvdz-f12-cabs/AutoCABS2+-.py", line 137, in process_primitives
    return concatenate_and_short(with_contraction_coeff_1_np.flat, outermost_decontracted[0,].flat, kind='mergesort')
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'with_contraction_coeff_1_np' is not defined. Did you mean: 'with_contraction_coeff_1'?

The program appeared to finish without issue, in the sense that I have a f.orca-formatted_basis file sitting in my directory, but because of the error I have no idea if those numbers are reliable.

Do you have any idea what this error might refer to, and if it will be affecting the results?

**Comment by isolated-matrix** [comment]
Yep, that's the one.

I'm running this on my MacBook Pro M1 Max, running macOS Sequoia 15.1.1 (in case that makes any difference). I'm using Python 3.12.7 (the latest release, I think).

The file should be attached below (had to add a `.txt` extension to allow it to upload).
[f.orca.txt](https://github.com/user-attachments/files/17978892/f.orca.txt)

**Comment by msemidalas** [comment]
Welp,  it's apparently a bug that slipped in while updating the code but it's easy to fix. 
Simply remove the '_np' from the variable name in line 137 of AutoCABS2+-.py
 The new line becomes:
return concatenate_and_short(with_contraction_coeff_1.flat, outermost_decontracted[0,].flat, kind='mergesort')

I will push this change into Github. Attached is the output and the modified Python script:

Basis set file in an ORCA format was found.
Chosen element is:F

 S main orbital exponents with contraction coefficient equal to 1:
 [[0.09158]
 [0.3041 ]
 [2.257  ]]

 S main orbital exponents with contraction coefficient not equal to 1:
 [[8.815e-01]
 [7.950e+00]
 [2.142e+01]
 [6.062e+01]
 [1.875e+02]
 [6.645e+02]
 [2.923e+03]
 [1.950e+04]]

 P main orbital exponents with contraction coefficient equal to 1:
 [[0.07361]
 [0.2672 ]
 [0.9132 ]
 [2.93   ]]

 P main orbital exponents with contraction coefficient not equal to 1:
 [[ 9.926]
 [43.88 ]]

 D main orbital exponents with contraction coefficient equal to 1:
 [[0.194 ]
 [0.5846]
 [1.9183]]

 D main orbital exponents with contraction coefficient not equal to 1:
 []

 F main orbital exponents with contraction coefficient equal to 1:
 []

 F main orbital exponents with contraction coefficient not equal to 1:
 []

 G main orbital exponents with contraction coefficient equal to 1:
 []

 G main orbital exponents with contraction coefficient not equal to 1:
 []

 H main orbital exponents with contraction coefficient equal to 1:
 []

 H main orbital exponents with contraction coefficient not equal to 1:
 []

 I main orbital exponents with contraction coefficient equal to 1:
 []

 I main orbital exponents with contraction coefficient not equal to 1:
 []

Geometric mean of S orbital exponents
 [[0.16688163]
 [0.51774912]
 [1.4105125 ]]

Geometric mean of P orbital exponents
 [[0.14024476]
 [0.49397069]
 [1.63574937]
 [5.39288235]]

Geometric mean of D orbital exponents
 [[0.33676758]
 [1.05897978]]

Geometric mean of F orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of G orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of H orbital exponents cannot be calculated from current main orbital exponents: []

Geometric mean of I orbital exponents cannot be calculated from current main orbital exponents: []

Summary of generated AutoCABS exponents
S
 [[1.4105125 ]
 [0.51774912]
 [0.16688163]]
P
 [[5.39288235]
 [1.63574937]
 [0.49397069]
 [0.14024476]]
D
 [[1.05897978]
 [0.33676758]]
F
 []
G
 []
H
 []
I
 []

 S orbital exponents, tight and a diffuse exponent:
 [0.0275794  0.16688163 0.51774912 1.4105125  5.77884175]

 P orbital exponents, tight (+2p) and a diffuse exponent:
 [2.02785632e-02 1.40244757e-01 4.93970687e-01 1.63574937e+00
 5.39288235e+00 3.36264423e+01 1.34505769e+02 5.38023077e+02]

 D orbital exponents, tight and a diffuse exponent:
 [0.06437906 0.33676758 1.05897978 6.29468849]
Generated F orbital exponents (extended version)
 [0.14724395 0.59718511 2.58184969]
Generated G orbital exponents (extended version)
 [0.29653313 1.24170938]

The AutoCABS was saved in ORCA, Turbomole, Psi4, and MOLPRO compatible formats.
Normal Termination
Best,
Emmanouil
    On Monday, December 2, 2024 at 03:58:09 PM GMT+2, isolated-matrix ***@***.***> wrote:  
 
 


Yep, that's the one.

The file should be attached below (had to add a .txt extension to allow it to upload).
f.orca.txt

**Comment by isolated-matrix** [comment]
Working now, thank you!

**Comment by msemidalas** [comment]
Fantastic! BTW, what's your name?

Feel free to contact if any others issues arise.

Best,
Emmanouil
   On Tuesday, December 3, 2024 at 11:00:54 AM GMT+2, isolated-matrix ***@***.***> wrote:  
 
 


Working now, thank you!

**Comment by isolated-matrix** [comment]
Sorry, I'm Matthew. Thank you again!
